version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfileflask
    image: flask-redis:1.0
    environment:
      - FLASK_ENV=developement
    ports:
      - 5000:5000
  redis:
    image: redis:4.0.11-alpine